; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.x"

; Modules
projects[addressfield][subdir] = "contrib"
projects[ctools][subdir] = "contrib"
projects[devel][subdir] = "contrib"
projects[entity][subdir] = "contrib"
projects[imageapi_optimize][subdir] = "contrib"
projects[imagecache_external][subdir] = "contrib"
projects[xautoload][subdir] = "contrib"

; Themes
projects[basic][version] = "4.2"

; Modules
projects[nt2][type] = "module"
projects[nt2][download][type] = "git"
projects[nt2][download][url] = "https://github.com/Neontabs/nt2.git"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[nt2_theme][type] = "theme"
projects[nt2_theme][download][type] = "git"
projects[nt2_theme][download][url] = "https://github.com/Neontabs/nt2_theme.git"

