<?php

/**
 * @file
 * NT2 Entity Module File
 */
error_reporting(E_ALL);
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);

define("COTTAGE_TAG_VOCAB_MACHINE_NAME", "cottage_tag_vocab");

function nt2_entity_entity_info() {
	$info = array();

	$info['cottage'] = array(
		'label' => t('Cottage Entity'),
		'base table' => 'cottages',
		'entity keys' => array(
			'id' => 'id',
			'label' => 'name'
		),
		'module' => 'nt2_entity',
		'entity class' => 'Entity',
		'controller class' => 'nt2EntityEntityController',
	);

	return $info;
};

function nt2_entity_menu() {
  $items = array();

  $items['nt2_test'] = array(
		'title' => 'nt2_test',
		'page callback' => 'nt2_entity_test_view',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

  $items['admin/config/nt2_entity'] = array(
    'title' => 'NT2 Entity',
    'position' => 'right',
    'weight' => -25,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
  );

  $items['admin/config/nt2_entity/entity'] = array(
    'title' => 'NT2 Entity',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nt2_entity_admin_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'nt2_entity.admin.inc',
  );

  return $items;
}

/**
 * Create a taxonomy term and return the tid.
 */
function create_taxonomy_term($name, $vid) {
	$term = new stdClass();
	$term->name = $name;
	$term->vid = $vid;
	taxonomy_term_save($term);
	return $term->tid;
}

function taxonomy_term_exists($name) {
	$term = taxonomy_get_term_by_name($name, COTTAGE_TAG_VOCAB_MACHINE_NAME);
	
	if(sizeof($term) > 0) {
		return TRUE;
	}
	
	return FALSE;
}

function create_vocabulary_from_attrib_list($attribs) {
	$vid = variable_get('nt2_entity_vocab_id');

	foreach ($attribs as $attrib) {
		$exists = taxonomy_term_exists($attrib["group"]);
		
		#Check if group parent of hierarchy exists; if it doesn't then add it to the hierarchy.
		if(!$exists) {
			create_taxonomy_term($attrib["group"], $vid);
		}


	}
}

function nt2_entity_test_view() {
	$items = array();

	//Test that the api works
	// $path = sprintf('property/' . strtoupper("A241") . '_ZZ');
	// $data = NeontabsIO::getInstance()->get($path);
	// dpm($data);


	$data = NeontabsIO::getInstance()->get("/");

	dpm($data["constants"]["attributes"]);

	create_vocabulary_from_attrib_list($data["constants"]["attributes"]);

	//Load the first cottage in the database (added manually)
	$cottages = entity_load('cottage', FALSE);
	$list = entity_view('cottage', $cottages);

	foreach ($list['cottage'] as $cottage) {
		$items[] = drupal_render($cottage);
	}


	// if(!isset($cottages[1000])) {
	// 	$entity = entity_create('cottage', array('id' => 1000));
	// 	$entity->reference = t('6969');
	// 	$entity->brandcode = t('6969');
	// 	$entity->name = t('Spring House');
	// 	$entity->save();
	// }

	return implode($items);
}