<?php

// error_reporting(E_ALL);
// ini_set('display_errors', TRUE);
// ini_set('display_startup_errors', TRUE);

function nt2_entity_entity_info() {
	$info = array();

	$info['cottage'] = array(
		'label' => t('Cottage Entity'),
		'base table' => 'cottages',
		'entity keys' => array(
			'id' => 'id',
			'label' => 'name'
		),
		'module' => 'nt2_entity',
		'entity class' => 'Entity',
		'controller class' => 'nt2EntityEntityController',
	);

	return $info;
};

function nt2_entity_menu() {
	$items['nt2_test'] = array(
		'title' => 'nt2_test',
		'page callback' => 'nt2_entity_test_view',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	return $items;
}

/**
 * Create a taxonomy term and return the tid.
 */
function create_taxonomy_term($name, $vid) {
	$term = new stdClass();
	$term->name = $name;
	$term->vid = $vid;
	taxonomy_term_save($term);
	return $term->tid;
}

function create_vocabulary_from_attrib_list($attribs) {
	foreach ($attribs as $attrib) {
		dpm($attrib);
		create_taxonomy_term($attrib["label"], variable_get('nt2_entity_vocab_id'));
	}
}

function nt2_entity_test_view() {
	$items = array();

	//Test that the api works
	// $path = sprintf('property/' . strtoupper("A241") . '_ZZ');
	// $data = NeontabsIO::getInstance()->get($path);
	// dpm($data);


	$data = NeontabsIO::getInstance()->get("/");

	dpm($data["constants"]["attributes"]);

	create_vocabulary_from_attrib_list($data["constants"]["attributes"]);

	//Load the first cottage in the database (added manually)
	$cottages = entity_load('cottage', array(1, 2, 3));
	$list = entity_view('cottage', $cottages);

	foreach ($list['cottage'] as $cottage) {
		$items[] = drupal_render($cottage);
	}


	// if(!isset($cottages[1000])) {
	// 	$entity = entity_create('cottage', array('id' => 1000));
	// 	$entity->reference = t('6969');
	// 	$entity->brandcode = t('6969');
	// 	$entity->name = t('Spring House');
	// 	$entity->save();		
	// }

	return implode($items);
}