<?php

/**
 * @file
 * Contains nt8propertyshortlist.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nt8propertyshortlist_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nt8propertyshortlist module.
    case 'help.page.nt8propertyshortlist':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides shortlist functionality to the nt8property module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function nt8propertyshortlist_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'nt8propertyshortlist/nt8propertyshortlist_lib';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function nt8propertyshortlist_preprocess_node__property(&$variables) {
  $propNode = $variables['node'];

  $propRef = $propNode->get('field_cottage_reference_code')->getValue()[0]['value'];

  $shortlistService = \Drupal::getContainer()->get('nt8propertyshortlist.service');
  $is_on_shortlist = $shortlistService->getEntry($propRef);

  if($is_on_shortlist) $variables['nt8propertyshortlist.on_shortlist'] = TRUE;
}

/**
 * Implements hook_theme().
 */
function nt8propertyshortlist_theme() {
  return [
    'nt8propertyshortlist' => [
      'render element' => 'children',
    ],
  ];
}
