<?php

/**
 * @file
 * Contains nt8search.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nt8search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nt8search module.
    case 'help.page.nt8search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Search module for Neontabs 8') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function nt8search_theme() {
  return [
    'nt8search' => [
      'template' => 'nt8search',
      'render element' => 'children',
    ],
  ];
}
