<?php

/**
 * @file
 * NT8Booking Enquiry functions.
 */

/**
 * Implements hook_menu().
 */
function nt8booking_enquiry_menu() {
  $items = array();

  $items['nt8booking_enquiry'] = array(
    'title' => 'NT8Booking Enquiry',
    'page callback' => array('nt8booking_enquiry_page'),
    'access arguments' => array('access content'),
  );

  $items['admin/config/package/nt8booking_enquiry'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nt8booking_enquiry_admin_form'),
    'title' => 'NT8Booking Enquiry Form',
    'access arguments' => array('administer NT8Booking Enquiry'),
    'file' => 'nt8booking_enquiry.admin.inc',
  );

  $items['admin/config/package/nt8booking_enquiry/nt8booking_enquiry'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nt8booking_enquiry_admin_form'),
    'title' => 'NT8Booking Enquiry Form',
    'access arguments' => array('administer NT8Booking Enquiry'),
    'file' => 'nt8booking_enquiry.admin.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 10,
  );

  return $items;
}


/**
 * Implements hook_menu().
 */
function nt8booking_enquiry_permission() {
  return array(
    'administer NT8Booking Enquiry' => array(
      'title' => t('Administer NT8Booking Enquiry'),
      'description' => t('Perform administration tasks for NT8Booking Enquiry.'),
    ),
  );
}

/**
 * Default action for NT8Booking Enquiry
 */
function nt8booking_enquiry_page() {
  return 'NT8Booking Enquiry place holder text.';
}

/**
 * Implements hook_nt8_booking_enquiry_create_alter().
 */
function nt8booking_enquiry_nt8_booking_enquiry_create_alter(&$enquiry_info, $data) {
  if (!$enquiry_info['success']) {
    // We set a default message, this should be overriden per brand.
    $message = json_encode($data, JSON_PRETTY_PRINT);
    $enquiry_info['message'] = $message;
  }
}
