---

dependencies: []

galaxy_info:
  author: danbohea
  description: Drush for Linux
  license: MIT
  min_ansible_version: 1.4
  platforms:
  - name: Debian
    versions:
    - jessie
    - wheezy
  - name: EL
    versions:
    - 6
    - 7
  - name: Ubuntu
    versions:
    - precise
    - trusty
  categories:
    - web
