<?php

$form['reload_tax_tag'] = array(
  '#type' => 'submit',
  '#value' => 'Reload Tags',
  '#submit' => array('nt2_entity_admin_form_reload_tax_tag'),
);

$form['reload_tax_loc'] = array(
  '#type' => 'submit',
  '#value' => 'Reload Locations',
  '#submit' => array('nt2_entity_admin_form_reload_tax_loc')
);

function nt2_node_type_menu() {
  $items = array();

  $items['nt2_node_type_test'] = array(
    'title' => 'nt2_node_type_test',
    'page arguments' => array(1, 2),
    'page callback' => 'nt2_node_type_test_view',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM
  );

  $items['nt2_node_type_test/%/node'] = array(
    'title' => 'nt2_node_type_test',
    'page callback' => 'nt2_node_type_test_view',
    'page arguments' => array(1, 2),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM
  );

  $items['nt2_node_type_test/%/teaser'] = array(
    'title' => 'nt2_node_type_test',
    'page callback' => 'nt2_node_type_test_view',
    'page arguments' => array(1, 2),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM
  );

  // Admin pages

  $items['admin/config/nt2/entity'] = array(
    'title' => 'Property nodes',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nt2_node_type_admin_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'nt2_node_type.admin.inc',
  );


  $items['admin/config/nt2/entity/reload_atts'] = array(
    'title' => 'Refresh Attributes',
    'page callback' => 'nt2_entity_admin_form_reload_tax_tag',
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'nt2_node_type.admin.inc',
  );

  $items['admin/config/nt2/entity/reload_locs'] = array(
    'title' => 'Refresh locations',
    'page callback' => 'nt2_entity_admin_form_reload_tax_loc',
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'nt2_node_type.admin.inc',
  );

  return $items;
}

function nt2_node_type_test_view($propref, $type) {

  $node = CottageNodeManager::loadNode($propref);
  $node_output = nt2_node_type_node_render_array($node);

  return $node_output;
}

function nt2_node_type_node_view($node, $view_mode, $langcode) {
    if ($node->type=="cottage_entity"){
        if ($view_mode == 'full'){
            $node_output = nt2_node_type_node_render_array($node);
            $node->content['nt2_node'] = $node_output;
        }
        return $node;
    }
}

function nt2_node_type_node_render_array(&$node) {
    $render_array = array();

    $cottage_info_definition = array(
      '#theme' => 'nt2_node_type_info',
      '#title' => $node->title,
      '#reference' => $node->cottage_reference["und"][0]["value"],
      '#slug' => $node->cottage_slug["und"][0]["value"],
      '#name' => $node->cottage_name["und"][0]["value"],
    );

    $render_array['definition'] = $cottage_info_definition;

    $render_array['cottage_name'] = array(
        '#type' => 'markup',
        '#markup' => $node->title,
        '#prefix' => '<h2>',
        '#suffix' => '</h2>',
    );

    // Build images array.
    $render_array['images'] = array(
        '#prefix' => '<ul>',
        '#suffix' => '</ul>',
    );

    $images = $node->cottage_images['und'];
    $index = 0;
    
    foreach ($images as $image) {
        list($alt, $title, $url) = explode("\n", $image['value']);

        $_image = array(
            '#prefix' => '<li>',
            '#suffix' => '</li>',
            '#theme' => 'imagecache_external',
            '#path' => $url,
            '#style_name' => 'thumbnail',
            '#alt' => $alt,
            '#title' => $title,
        );

        $render_array['images']['image' . sprintf('%02d', $index++)] = $_image;
    }
    
    // Process the address using a custom template.
    $address = array(
      '#theme' => 'nt2_node_type_address',
      '#address' => $node->cottage_fieldaddress['und'][0],
    );

    $render_array['address'] = $address;

    $accommodation_definition = array(
      '#theme' => 'nt2_node_type_accommodation',
      '#accommodates' => $node->cottage_accomodates["und"][0]["value"],
      '#bedrooms' => $node->cottage_bedrooms["und"][0]["value"],
      '#pets' => $node->cottage_pets["und"][0]["value"],
      '#changeover' => $node->cottage_changeoverday["und"][0]["value"],
    );

    $render_array['accommodation'] = $accommodation_definition;

    $description_definition = array(
      '#theme' => 'nt2_node_type_description',
      '#description' => $node->cottage_description["und"][0]["value"],
      '#description_short' => $node->cottage_description_short["und"][0]["value"],
      '#description_teaser' => $node->cottage_description_teaser["und"][0]["value"],
    );

    $render_array['description'] = $description_definition;



    $render = array(
        'property' => $render_array,
    );

    dpm($render, 'Property Render array');
    dpm($node, 'Node');

    return $render;
}

function nt2_node_type_theme() {
  return array(
    'nt2_node_type_address' => array(
      'variables' => array(
        'address' => NULL,
      ),
      'template' => 'templates/nt2_node_type_address'
    ),
    'nt2_node_type_accommodation' => array(
      'variables' => array(
        'accommodates' => NULL,
        'bedrooms' => NULL,
        'pets' => NULL,
        'changeover' => NULL,
      ),
      'template' => 'templates/nt2_node_type_accommodation'
    ),
    'nt2_node_type_description' => array(
      'variables' => array(
        'description' => NULL,
        'description_short' => NULL,
        'description_teaser' => NULL,
      ),
      'template' => 'templates/nt2_node_type_description'
    ),
    'nt2_node_type_info' => array(
      'variables' => array(
        'title' => NULL,
        'reference' => NULL,
        'slug' => NULL,
        'name' => NULL,
      ),
      'template' => 'templates/nt2_node_type_info'
    )
  );
}


function nt2_node_type_preprocess_nt2_node_type_address(&$vars) {
  // dpm($vars, '$vars before');

  if (isset($vars['address'])) {
    $vars['addr1'] = $vars["address"]["thoroughfare"];
    $vars['addr2'] = $vars["address"]["premise"];
    $vars['county'] = $vars["address"]["locality"];
    $vars['postcode'] = $vars["address"]["postal_code"];
  }

  // dpm($vars, '$vars after');
}
