<?php

/**
 * @file
 * The module file for nt2_node_type.
 */

/**
 * Implements hook_menu.
 */
function nt2_node_type_menu() {
  $items = array();

  $items['nt2_node_type_test'] = array(
    'title' => 'nt2_node_type_test',
    'page arguments' => array(1, 2),
    'page callback' => 'nt2_node_type_test_view',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM
  );

  $items['nt2_node_type_test/%/node'] = array(
    'title' => 'nt2_node_type_test',
    'page callback' => 'nt2_node_type_test_view',
    'page arguments' => array(1, 2),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM
  );

  $items['nt2_node_type_test/%/teaser'] = array(
    'title' => 'nt2_node_type_test',
    'page callback' => 'nt2_node_type_test_view',
    'page arguments' => array(1, 2),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM
  );

  // Admin pages.
  $items['admin/config/nt2/entity'] = array(
    'title' => 'Property nodes',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nt2_node_type_admin_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'nt2_node_type.admin.inc',
  );

  $items['admin/config/nt2/entity/reload_atts'] = array(
    'title' => 'Refresh Attributes',
    'page callback' => 'nt2_entity_admin_form_reload_tax_tag',
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'nt2_node_type.admin.inc',
  );

  $items['admin/config/nt2/entity/reload_locs'] = array(
    'title' => 'Refresh locations',
    'page callback' => 'nt2_entity_admin_form_reload_tax_loc',
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'nt2_node_type.admin.inc',
  );

  return $items;
}
