# Schema for the configuration files of the Config Entity Example module.

# This schema tells the config system how to read our config YML files.
# See for example the file config/config_entity_example.robot.marvin.yml, which
# contains our default config entity.

# Documentation for schema files like this one is located here:
# https://drupal.org/node/1905070

nt8booking_details.settings:
  type: mapping
  label: 'NT8 Booking Details'
  mapping:
    titles_list:
      label: 'Titles'
      type: string
  mapping:
    other_code:
      label: 'Other code'
      type: string
  mapping:
    age_list:
      label: 'Age List'
      type: string
