FROM neontabs/nt8:latest
LABEL authors="oliver@neontribe.co.uk, toby@neontribe.co.uk"

WORKDIR /opt/nt8

COPY startup.tester.sh /usr/local/bin/startup.sh
RUN chmod 777 /usr/local/bin/startup.sh

RUN echo /usr/local/bin/startup.sh >> /root/.bash_history

ENTRYPOINT ["/usr/local/bin/startup.sh"]