---
- name: Install NTP
  sudo: yes
  apt: pkg=ntp state=latest
  
- name: Set timezone variables
  sudo: yes
  copy: 
    content='{{ timezone }}'
    dest=/etc/timezone
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: update timezone
  
- name: Set NTP Server pools
  replace: dest=/etc/ntp.conf regexp='ubuntu.pool.ntp.org' replace='europe.pool.ntp.org' backup=no
