<?php

/**
 * @file
 * This file contains most of the hooks necessary for the module to function.
 */

/**
 * Implements hook_menu().
 */
function nt2_search_menu() {
  $items = array();

  $items['nt2_search'] = array(
    'title' => 'NT2 Search',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'page callback' => 'nt2_search_page',
  );

  $items['admin/config/nt2/terms'] = array(
    'title' => 'Search',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nt2_search_admin_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'nt2_search.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function nt2_search_theme() {
  $theme = array();

  $theme['nt2_search_admin_overview_form_table'] = array(
    'render element' => 'element',
    'file' => 'nt2_search.admin.inc',
  );

  return $theme;
}

/**
 * Implements hook_page().
 */
function nt2_search_page() {
  /* TODO
   * The below conditional prevents ::page() being called twice when a form is submitted on the search results page, however, it achieves this by using the variable $_SERVER, which Drupal abstracts away, so should be avoided. Furthermore, an edge-case is if the form being submitted from the results page submits to the same page with a GET request; in this scenario the bug would still occur.
   *
   * Ideally, this problem may be fixed cleanly with Drupal, by preventing ::page() from being performed in any scenario other than Drupal internally redirecting to it, or similar.
   */
  if ($_SERVER['REQUEST_METHOD'] === 'GET') {
    $data = NT2Search::page();
    drupal_alter('nt2_search_results', $data);
    return $data;
  }
  return array();
}

/**
 * Implements hook_block_info().
 */
function nt2_search_block_info() {
  $blocks = array();

  $blocks['nt2_q_search'] = array(
    'info' => t('NT2: Quick search form'),
    'cache' => DRUPAL_NO_CACHE,
    'region' => 'sidebar_first',
    // Status of 1 means enabled.
    'status' => 1,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function nt2_search_block_view($delta) {
  $block = array();

  if ($delta == 'nt2_q_search') {
    $block['subject'] = t('Quick Search');
    $block['content'] = drupal_get_form('nt2_search_quick_form');
  }
  elseif ($delta == 'nt2_a_search') {
    $block['subject'] = t('Advanced Search');
    $block['content'] = drupal_get_form('nt2_search_advanced_form');
  }

  return $block;
}

/**
 * Implements hook_form().
 */
function nt2_search_quick_form() {
  return NT2Search::quickSearchForm();
}

/**
 * Implements hook_form_validate().
 */
function nt2_search_quick_form_validate($form, &$form_state) {
  // Do validation.
  dpm(__METHOD__);
}

/**
 * Implements hook_form_submit().
 */
function nt2_search_quick_form_submit($form, &$form_state) {
  // Do submit.
  NT2Search::quickSearchFormSubmit($form, $form_state);
}

/**
 * Implements hook_form().
 */
function nt2_search_advanced_form() {
  return array();
}
