---
# tasks file for postfix
- name: configure debconf
  sudo: true
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: postfix_debconf_selections
  tags: [configuration, postfix, postfix-install]

- name: install package
  sudo: true
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items: postfix_install
  tags: [configuration, postfix, postfix-install]

- name: configure mailname
  sudo: true
  template:
    src: etc/mailname.j2
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  tags: [configuration, postfix, postfix-mailname]

- name: update configuration file
  sudo: true
  template:
    src: etc/postfix/main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  tags: [configuration, postfix, postfix-configuration]

- name: configure aliases
  sudo: true
  lineinfile:
    dest: /etc/aliases
    regexp: '^{{ item.user }}:\s+{{ item.alias }}'
    line: '{{ item.user }}: {{ item.alias }}'
    owner: root
    group: root
    mode: 0644
  with_items: postfix_aliases
  when: postfix_aliases
  notify:
    - new aliases
    - restart postfix
  tags: [configuration, postfix, postfix-aliases]

- name: start and enable service
  sudo: true
  service:
    name: postfix
    state: started
    enabled: yes
  tags: [configuration, postfix, postfix-start-enable-service]

- name: add email alias for root@
  sudo: true
  template:
    src: etc/postfix/generic.j2
    dest: /etc/postfix/generic
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  tags: [configuration, postfix, postfix-configuration]

- name: Tighten Postfix
  sudo: true
  shell: sudo postconf -e 'disable_vrfy_command=yes'
  shell: sudo postconf -e 'smtp_tls_security_level = may'
  shell: sudo postconf -e 'smtpd_tls_security_level = may'
  shell: sudo postconf -e 'smtpd_tls_auth_only = no'
  shell: sudo postconf -e 'smtp_tls_note_starttls_offer = yes'
  shell: sudo postconf -e 'smtpd_tls_key_file = /etc/apache2/ssl/ssl.key'
  shell: sudo postconf -e 'smtpd_tls_cert_file = /etc/apache2/ssl/ssl.crt'
  shell: sudo postconf -e 'smtpd_tls_CAfile = /etc/apache2/ssl/chain.crt'
  shell: sudo postconf -e 'smtpd_tls_loglevel = 1'
  shell: sudo postconf -e 'smtpd_tls_received_header = yes'
  shell: sudo postconf -e 'smtpd_tls_session_cache_timeout = 3600s'
  shell: sudo postconf -e 'tls_random_source = dev:/dev/urandom'
  shell: sudo postconf -e 'myhostname = {{ servername }}'
  shell: sudo postconf -e 'mydestination = localhost.localdomain, localhost'
  shell: sudo postconf -e 'smtp_generic_maps = hash:/etc/postfix/generic'
