<?php

/**
 * @file
 * Contains nt8images.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nt8images_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nt8images module.
    case 'help.page.nt8images':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Handles images in Neontabs 8') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function nt8images_theme() {
  return [
    'nt8images' => [
      'template' => 'nt8images',
      'render element' => 'children',
    ],
  ];
}
