<?php

/**
 * @file
 * Contains nt8booking_details.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function nt8booking_details_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nt8booking_details module.
    case 'help.page.nt8booking_details':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Booking path details form') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_nt8_booking_enquiry_create_alter().
 */
function nt8booking_details_nt8_booking_enquiry_create_alter(&$enquiry_info, $data) {
  if ($enquiry_info['success']) {
    // We just need to set a redirect here.
    $params = array('booking_id' => $data['bookingId']);
    $url = Url::fromRoute('nt8booking_details.details', $params);
    $enquiry_info['redirect'] = $url;
  }
}
