---

- name: Set up drush
  file:
    src: /vagrant/vendor/drush/drush/drush
    dest: /usr/local/bin/drush
    state: link
  when: installer_root == "/vagrant/web"

- name: Check if site is installed
  stat:
    path: "{{ installer_root }}/sites/default/files/.ht.sqlite"
  register: sqlite

- name: Install the default site
  shell: drush -y site-install --db-url=mysql://nt8:nt8@localhost/nt8 --db-su=root --db-su-pw=change_me --account-mail=${USER}@neontribe.co.uk --account-name=superadmin --site-mail=${USER}@neontribe.co.uk --site-name=EntyAte
  args:
    chdir: "{{ installer_root }}"
  when: ( not sqlite.stat.exists ) or ( sqlite.stat.size == 0 )

- name: Enable the NT8 Theme
  shell: drush -y en nt8_theme
  args:
    chdir: "{{ installer_root }}"

- name: Set default theme
  shell: drush -y config-set system.theme default nt8_theme
  args:
    chdir: "{{ installer_root }}"

- name: Enable the NT8 Rest Module
  shell: drush -y en nt8tabsio
  args:
    chdir: "{{ installer_root }}"

- name: Enable the NT8 Property Module
  shell: drush -y en nt8property
  args:
    chdir: "{{ installer_root }}"

- name: Enable the NT8 Search and Map Modules
  shell: drush -y en nt8map nt8search
  args:
    chdir: "{{ installer_root }}"

- name: Import properties
  shell: drush -y nt8-import-all
  args:
    chdir: "{{ installer_root }}"
