---

- name: Ensure .ssh directory exists.
  file:
    path: .ssh
    state: directory
    mode: 0700
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Ensure GitHub deploy key is present on the server.
  copy:
    src: "{{ app.ssh_private_key }}"
    dest: /home/{{ ansible_ssh_user }}/.ssh/id_rsa
    mode: 0600
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

# See: https://stackoverflow.com/a/37096534/100134
- name: Ensure setfacl support is present.
  package: name=acl

- name: Clone the code repository to the docroot.
  git:
    repo: git@bitbucket.org:neontabs/{{ app.brand }}.git
    dest: /var/tmp/repo
    accept_hostkey: yes
    key_file: /home/{{ ansible_user }}/.ssh/id_rsa
    force: yes
    depth: 1
    recursive: yes
    update: yes
  become_user: "{{ ansible_user }}"

- name: Deploy the site
  shell: composer --no-ansi deploy
  args:
    chdir: /var/tmp/repo
  environment:
    DBNAME: "{{ mysql.database }}"
    DBUSER: "{{ mysql.user }}"
    DBHOST: "{{ mysql.host }}"
    DBPASS: "{{ mysql.password }}"
    TARGET: "{{ apache.docroot }}"
