---
# application tasks to be customized and to run after the main provision

- name: Set doc root to /vagrant/web
  lineinfile:
    dest: /etc/apache2/sites-enabled/000-default.conf
    regexp: '^    DocumentRoot /vagrant'
    line: '    DocumentRoot /vagrant/web'
  notify: restart apache

- name: Set doc root to /vagrant/web
  file:
    src: /vagrant/vendor/drush/drush/drush
    dest: /usr/local/bin/drush
    state: link

- name: Check if site is installed
  stat:
    path: /vagrant/web/sites/default/files/.ht.sqlite
  register: sqlite

- name: Install the default site
  shell: drush -y site-install --db-url=sqlite://sites/default/files/.ht.sqlite --account-mail=${USER}@neontribe.co.uk --account-name=superadmin --site-mail=${USER}@neontribe.co.uk --site-name=EntyAte
  args:
    chdir: /vagrant/web
  when: not sqlite.stat.exists

- name: Enable the NT8 Theme
  shell: drush -y en nt8_theme
  args:
    chdir: /vagrant/web

- name: Set default theme
  shell: drush -y config-set system.theme default nt8_theme
  args:
    chdir: /vagrant/web

- name: Enable the NT8 Rest Module
  shell: drush -y en nt8tabsio
  args:
    chdir: /vagrant/web

- name: Enable the NT8 Property Module
  shell: drush -y en nt8property
  args:
    chdir: /vagrant/web

- name: Enable the NT8 Search and Map Modules
  shell: drush -y en nt8map nt8search
  args:
    chdir: /vagrant/web

- name: Import properties
  shell: drush -y nt8-import-all
  args:
    chdir: /vagrant/web
