---
galaxy_info:
  author: Pierre Buyle & Pierre Paul Lefebvre
  description: Manage a simple exim4 configuration
  company: Floe design + technologies
  license: BDS
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
  - networking
  - packaging
dependencies: []
