FROM tobybatch/nt8installer
MAINTAINER tobias@neontribe.co.uk

COPY startup.tester.sh /usr/local/bin/startup.sh
RUN chmod 777 /usr/local/bin/startup.sh

RUN echo /usr/local/bin/startup.sh >> /root/.bash_history

EXPOSE 8888
ENTRYPOINT ["/usr/local/bin/startup.sh"]
# ENTRYPOINT ["/bin/bash"]

# vim: set filetype=dockerfile expandtab tabstop=2 shiftwidth=2 autoindent smartindent:
