<?php

/**
 * @file
 * Contains nt8landingpage.module.
 */

use Drupal\block\Entity\Block;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nt8landingpage_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nt8landingpage module.
    case 'help.page.nt8landingpage':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Defines the landing page content type and its&#039; functionality.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_view().
 */
function nt8landingpage_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  $property_service = \Drupal::getContainer()->get('nt8property.property_methods');
  $search_service   = \Drupal::getContainer()->get('nt8search.methods');

  if ($view_mode === 'full') {
    $entity_type = $entity->bundle();
    switch ($entity_type) {
      case 'landing_page':

        $build['#cache'] = [
          'contexts' => [
            'url.path',
            'url.query_args',
          ]
        ];

        $filter_string = $property_service->getNodeFieldValue($entity, 'field_tabs_filter_string', 0, 'value');
        $filter_array = [];
        parse_str($filter_string, $filter_array);

        $search_service->performSearchFromParams($filter_array, TRUE);

        // @TODO: Use a better module to manage block visiblity.
        // There's a module which allows for specific block view settings.
        // We should use that.
        $block = Block::load('neontabs8searchresultsblock');
        $render = \Drupal::entityTypeManager()
          ->getViewBuilder('block')
          ->view($block);
        $build['content']['results'] = $render;
        break;
    }
  }
}

/**
 * Implements hook_theme().
 */
function nt8landingpage_theme() {
  return [
    'nt8landingpage' => [
      'template' => 'nt8landingpage',
      'render element' => 'children',
    ],
  ];
}
