<?php

/**
 * @file
 * Contains nt8property.module.
 */

use Drupal\Core\Entity\Entity\EntityViewDisplay;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\nt8property\NT8PropertyViewEvent;

/**
 * Implements hook_help().
 */
function nt8property_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nt8property module.
    case 'help.page.nt8property':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Neontabs Property') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_view().
 */
function nt8property_node_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, EntityViewDisplay $display, $view_mode) {
  if ($view_mode === 'full') {
    $entity_type = $entity->bundle();
    switch ($entity_type) {
      case 'property':
        $propertyViewEvent = new NT8PropertyViewEvent(
          $entity->get('field_cottage_reference_code')->getValue()
        );

        $dispatcher = \Drupal::service('event_dispatcher');
        $dispatcher->dispatch(NT8PropertyViewEvent::NAME, $propertyViewEvent);
        break;
    }
  } else if($view_mode === 'teaser') {
    // TODO: Fire event for teasers.
  }
}

/**
 * Implements hook_theme().
 */
function nt8property_theme() {
  return [
    'nt8property' => [
      'template' => 'nt8property',
      'render element' => 'children',
    ],
    'field_cottage_rating_formatter' => [
      'template' => 'nt8property-field-cottage-rating-formatter',
      'variables' => [
        'value' => NULL,
      ],
    ],
    'field_cottage_pricing_formatter' => [
      'template' => 'nt8property-field-cottage-pricing-formatter',
      'variables' => [
        'pricing_data' => NULL,
        'year' => NULL,
      ],
    ],
  ];
}
