---
- hosts: all
  become: true
  vars_files:
    - vars/all.yml
  roles:
    - server
    - vagrant_local
    - apache
    - mysql
    - sqlite
    - php
    - xdebug
    - composer
    - drush
    - app
