map-settings:
  zoom: 1
  lon: '51.482905'
  lat: '0'
  tiles: osmmap
  imagestyle: thumbnail
  image_width: 100
  image_height: 100
langcode: en
_core:
  default_config_hash: 2AUrD8nLfoR-Pf41H2_X2mlWinS6JMBxIRooU_DyzJQ
