---
- name: Update apt
  sudo: yes
  apt: update_cache=yes cache_valid_time=3600

- name: Install Clamav packages
  sudo: yes
  apt: pkg="{{ item }}" state=latest
  with_items:
    - clamav
  register: clamav_install

- name: Update virus definition
  sudo: yes
  command: freshclam --quiet

- name: Copy daily virus check
  sudo: yes
  template: src=daily.j2 dest="/etc/cron.daily/clamscan" mode=0755 owner=root group=root

- name: Copy weekly virus check
  sudo: yes
  template: src=weekly.j2 dest="/etc/cron.weekly/clamscan" mode=0755 owner=root group=root
